INSERT INTO ACCOUNT ( ID , FIRSTNAME , SECONDNAME , ACCOUNTNUMBER ) VALUES(1,'john','doe','1234');
INSERT INTO ACCOUNT ( ID , FIRSTNAME , SECONDNAME , ACCOUNTNUMBER ) VALUES(2,'jane','doe','1235');
INSERT INTO ACCOUNT ( ID , FIRSTNAME , SECONDNAME , ACCOUNTNUMBER ) VALUES(3,'jim','taylor','1236');